// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIjeBsWAP1AN4RKANmlYfTDkwt9qZvKUE',
    appId: '1:690089140261:web:5575b677cfff995ce45fcc',
    messagingSenderId: '690089140261',
    projectId: 'e-commerce-app-e337c',
    authDomain: 'e-commerce-app-e337c.firebaseapp.com',
    storageBucket: 'e-commerce-app-e337c.appspot.com',
    measurementId: 'G-SL82MZN7GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnG9HmmQPUB8oc0RIdIsTCHkTipDGll7o',
    appId: '1:690089140261:android:a5420f62334e3cfce45fcc',
    messagingSenderId: '690089140261',
    projectId: 'e-commerce-app-e337c',
    storageBucket: 'e-commerce-app-e337c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8EliapFOsjueslqBkeRDUPOKIEvn4AS4',
    appId: '1:690089140261:ios:053049952b3c4839e45fcc',
    messagingSenderId: '690089140261',
    projectId: 'e-commerce-app-e337c',
    storageBucket: 'e-commerce-app-e337c.appspot.com',
    iosBundleId: 'com.example.ecommereceapp',
  );
}
